services:
  postgres:
    container_name: database
    image: postgres:15
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: business-efficency
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root
    volumes:
      - rabbit_data:/rabbit/data

volumes:
  pgdata:
  rabbit_data:
