spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 11MB

server:
  servlet:
    context-path: /be

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

google:
  oauth:
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}
    redirect-uri: ${REDIRECTED_URI}
    auth-uri: ${AUTH_URI}
    token-url: ${TOKEN_URL}
    user-info-url: ${USER_INFO_URL}
    response-type: ${RESPONSE_TYPE}
    access_type: ${ACCESS_TYPE}
    prompt: ${PROMT}
    scope: ${SCOPE}
    grant-type: ${GRANT_TYPE}